services:
  api:
    build:
      context: .
    container_name: mamaopeai_rag_api
    ports:
      - "8090:8090"
    env_file:
      - .env  
    environment:
      - ENV=production
      - GOOGLE_APPLICATION_CREDENTIALS=/app/regal-autonomy-454806-d1-51289c3215c0.json
      - LOG_LEVEL=info
    restart: unless-stopped
    